import { makeLeedsProfile } from "./leedsProfileBase";

export const bathroomSpecialistsLeeds = makeLeedsProfile("bathroom-specialists", {
  "heroCopy": "Planning a bathroom refurbishment, shower installation or full refit in Leeds? Describe the room, layout and finish once, then compare bathroom specialists suited to the project.",
  "answer": {
    "title": "Looking for a bathroom specialist near you in Leeds?",
    "copy": "Enter the postcode and explain the existing room, sanitaryware, shower or bath, tiling and whether plumbing or electrical positions are changing. Suitable Leeds specialists can price the same scope."
  },
  "localContext": {
    "eyebrow": "Leeds bathroom projects",
    "title": "Rental standards and disposal arrangements are worth clarifying before strip-out",
    "intro": "Bathrooms often combine plumbing, tiling, ventilation and waste removal. In Leeds, rental-property context and trade-waste rules make a clear written scope especially useful.",
    "items": [
      {
        "title": "Selective licensing covers designated private-rented areas from February 2026",
        "text": "Leeds' current selective-licensing scheme applies to designated parts of six wards and includes conditions around property management and standards. It does not prescribe a particular bathroom contractor, but landlords should make sure refurbishment work supports the property's wider safety and repair obligations.",
        "source": {
          "label": "Leeds City Council — selective licensing",
          "url": "https://www.leeds.gov.uk/housing/information-for-landlords/selective-licensing"
        }
      },
      {
        "title": "Bathroom strip-out waste from paid trades needs a commercial route",
        "text": "Leeds City Council says waste generated by tradespeople, including plumbers and other home-improvement contractors, is business or trade waste and cannot be disposed of at household recycling centres as ordinary household waste. Ask whether sanitaryware, tiles and rubble removal are included.",
        "source": {
          "label": "Leeds City Council — trade and business waste",
          "url": "https://www.leeds.gov.uk/bins-and-recycling/recycling-sites"
        }
      }
    ]
  },
  "areaCopy": {
    "intro": "Bathroom specialists may cover Leeds by postcode and project size. Example areas include:",
    "sideTitle": "Describe the full room, not just the fittings",
    "sideCopy": "The quote should say whether strip-out, plumbing changes, waterproofing, tiling, ventilation, electrics, decorating and waste removal are included.",
    "noteLead": "Waterproofing is part of the system.",
    "noteText": "Ask how shower and wet-area backgrounds will be prepared and waterproofed before the visible tiles or panels go on."
  },
  "faq": [
    [
      "How much does a bathroom refurbishment cost in Leeds?",
      "The cost depends on room size, sanitaryware, layout changes, tiling, plumbing, electrics and the condition found after strip-out. Compare quotes against the same specification."
    ],
    [
      "Does selective licensing mean I need a particular bathroom contractor?",
      "No. The scheme regulates designated rental properties and landlord responsibilities; it does not appoint a required bathroom contractor."
    ],
    [
      "Who removes the old bathroom?",
      "Agree this before work starts. Leeds treats waste generated by paid trades as business or trade waste, so disposal should be included or clearly excluded from the quote."
    ],
    [
      "Should ventilation be part of the bathroom plan?",
      "Yes. Moisture control is important in bathrooms, especially where layouts or extract fans are changing."
    ],
    [
      "Do I have to hire a bathroom specialist who responds?",
      "No. There is no obligation to hire."
    ]
  ],
  "cta": {
    "title": "Ready to compare bathroom specialists in Leeds?",
    "copy": "Describe the room, layout and finish once, then compare interested Leeds bathroom specialists and full-scope quotes.",
    "buttonLabel": "Get Leeds bathroom quotes"
  }
});

export const drainageSpecialistsLeeds = makeLeedsProfile("drainage-specialists", {
  "heroCopy": "Blocked drain, recurring smell, slow drainage or a suspected pipe defect in Leeds? Describe the symptoms and affected fixtures once, then compare drainage specialists suited to the problem.",
  "answer": {
    "title": "Looking for a drainage specialist near you in Leeds?",
    "copy": "Enter the postcode and explain which drains or fixtures are affected, whether the problem is inside or outside and whether it is recurring. Suitable Leeds drainage specialists can judge whether clearance, CCTV or repair is likely."
  },
  "localContext": {
    "eyebrow": "Leeds drainage context",
    "title": "Pipe ownership and flood risk can change who should deal with the problem",
    "intro": "Before paying for extensive drainage work, establish whether the defect is on a private drain, a shared/public sewer or part of a wider surface-water issue.",
    "items": [
      {
        "title": "Yorkshire Water distinguishes private drains from public or shared sewers",
        "text": "Yorkshire Water says homeowners are generally responsible for drains serving only their own home up to the point where they connect with a public sewer or other disposal route. Shared drains serving more than one home are usually Yorkshire Water's responsibility, even when they run within a property boundary.",
        "source": {
          "label": "Yorkshire Water — pipework responsibility guide",
          "url": "https://www.yorkshirewater.com/media/444iqme5/whosepipeisit_leaflet.pdf"
        }
      },
      {
        "title": "Leeds manages flood risk from surface water, sewers and groundwater as well as rivers",
        "text": "Leeds City Council's Local Flood Risk Management Strategy covers ordinary watercourses, surface water, rainfall-related sewer flooding and groundwater alongside main-river risk. If several external drains surcharge during heavy rain, the issue may need broader investigation rather than repeated local unblocking.",
        "source": {
          "label": "Leeds City Council — Local Flood Risk Management Strategy",
          "url": "https://www.leeds.gov.uk/flooding/flood-risk-management-strategy"
        }
      }
    ]
  },
  "areaCopy": {
    "intro": "Drainage specialists may cover Leeds by postcode and urgency. Example areas include:",
    "sideTitle": "Say exactly where the problem appears",
    "sideCopy": "A blocked kitchen waste, external gully, inspection chamber and shared sewer are different jobs. Explain which fixtures back up, when it happens and whether neighbours are affected.",
    "noteLead": "Diagnosis can save unnecessary repair.",
    "noteText": "Recurring blockages may justify CCTV or further investigation rather than paying repeatedly for simple clearance."
  },
  "faq": [
    [
      "Who is responsible for a blocked drain in Leeds?",
      "It depends on the pipe. Yorkshire Water says a homeowner is generally responsible for a drain serving only their home until it connects with a public sewer, while shared drains and public sewers are usually Yorkshire Water's responsibility."
    ],
    [
      "When is a CCTV drain survey useful?",
      "It can help when blockages recur, damage is suspected or the route and condition of buried pipework are unclear."
    ],
    [
      "Does flood risk matter for drainage work in Leeds?",
      "Yes. Leeds' flood strategy covers surface water, sewer and groundwater flooding as well as rivers, so repeated external flooding may not be a simple local blockage."
    ],
    [
      "Should I pay for jetting before knowing whose pipe it is?",
      "For an urgent local blockage that may be reasonable, but for recurring or shared-pipe problems it is worth establishing responsibility before authorising larger repairs."
    ],
    [
      "Do I have to hire a drainage specialist who responds?",
      "No. There is no obligation to hire."
    ]
  ],
  "cta": {
    "title": "Ready to compare drainage specialists in Leeds?",
    "copy": "Describe the symptoms and affected drains once, then compare interested Leeds drainage specialists and diagnostic options.",
    "buttonLabel": "Get Leeds drainage quotes"
  }
});
