import type { ServiceSlug } from "./serviceIframe";

export type PublishedLocalServicePage = {
  service: ServiceSlug;
  city: string;
};

/**
 * Add a service slug here only when its top-level SEO landing page exists and is ready to index.
 * The sitemap reads this registry automatically.
 */
export const PUBLISHED_SERVICE_PAGES: readonly ServiceSlug[] = [
  "removal-companies",
  "cleaners",
  "tilers",
  "heating-engineers",
  "locksmiths",
  "pest-controllers",
  "tree-surgeons",
  "architects",
  "plasterers",
  "kitchen-fitters",
  "bathroom-specialists",
  "drainage-specialists",
  "driveway-specialists",
  "window-specialists",
];

/**
 * Add a location page here only after the route and its researched local content are complete.
 * `city` must be the URL slug used by the page, for example `croydon`.
 */
export const PUBLISHED_LOCAL_SERVICE_PAGES: readonly PublishedLocalServicePage[] = [
  { service: "removal-companies", city: "birmingham" },
  { service: "cleaners", city: "birmingham" },
  { service: "tilers", city: "birmingham" },
  { service: "heating-engineers", city: "birmingham" },
  { service: "locksmiths", city: "birmingham" },
  { service: "pest-controllers", city: "birmingham" },
  { service: "tree-surgeons", city: "birmingham" },
  { service: "architects", city: "birmingham" },
  { service: "plasterers", city: "birmingham" },
  { service: "kitchen-fitters", city: "birmingham" },
  { service: "bathroom-specialists", city: "birmingham" },
  { service: "drainage-specialists", city: "birmingham" },
  { service: "driveway-specialists", city: "birmingham" },
  { service: "window-specialists", city: "birmingham" },
  { service: "removal-companies", city: "manchester" },
  { service: "cleaners", city: "manchester" },
  { service: "tilers", city: "manchester" },
  { service: "heating-engineers", city: "manchester" },
  { service: "locksmiths", city: "manchester" },
  { service: "pest-controllers", city: "manchester" },
  { service: "tree-surgeons", city: "manchester" },
  { service: "architects", city: "manchester" },
  { service: "plasterers", city: "manchester" },
  { service: "kitchen-fitters", city: "manchester" },
  { service: "bathroom-specialists", city: "manchester" },
  { service: "drainage-specialists", city: "manchester" },
  { service: "driveway-specialists", city: "manchester" },
  { service: "window-specialists", city: "manchester" },
  { service: "removal-companies", city: "london" },
  { service: "cleaners", city: "london" },
  { service: "tilers", city: "london" },
  { service: "heating-engineers", city: "london" },
  { service: "locksmiths", city: "london" },
  { service: "pest-controllers", city: "london" },
  { service: "tree-surgeons", city: "london" },
  { service: "architects", city: "london" },
  { service: "plasterers", city: "london" },
  { service: "kitchen-fitters", city: "london" },
  { service: "bathroom-specialists", city: "london" },
  { service: "drainage-specialists", city: "london" },
  { service: "driveway-specialists", city: "london" },
  { service: "window-specialists", city: "london" },
  { service: "removal-companies", city: "leeds" },
  { service: "cleaners", city: "leeds" },
  { service: "tilers", city: "leeds" },
  { service: "heating-engineers", city: "leeds" },
  { service: "locksmiths", city: "leeds" },
  { service: "pest-controllers", city: "leeds" },
  { service: "tree-surgeons", city: "leeds" },
  { service: "architects", city: "leeds" },
  { service: "plasterers", city: "leeds" },
  { service: "kitchen-fitters", city: "leeds" },
  { service: "bathroom-specialists", city: "leeds" },
  { service: "drainage-specialists", city: "leeds" },
  { service: "driveway-specialists", city: "leeds" },
  { service: "window-specialists", city: "leeds" },
  { service: "removal-companies", city: "bristol" },
  { service: "cleaners", city: "bristol" },
  { service: "tilers", city: "bristol" },
  { service: "heating-engineers", city: "bristol" },
  { service: "locksmiths", city: "bristol" },
  { service: "pest-controllers", city: "bristol" },
  { service: "tree-surgeons", city: "bristol" },
  { service: "architects", city: "bristol" },
  { service: "plasterers", city: "bristol" },
  { service: "kitchen-fitters", city: "bristol" },
  { service: "bathroom-specialists", city: "bristol" },
  { service: "drainage-specialists", city: "bristol" },
  { service: "driveway-specialists", city: "bristol" },
  { service: "window-specialists", city: "bristol" },
  { service: "removal-companies", city: "southampton" },
  { service: "cleaners", city: "southampton" },
  { service: "tilers", city: "southampton" },
  { service: "heating-engineers", city: "southampton" },
  { service: "locksmiths", city: "southampton" },
  { service: "pest-controllers", city: "southampton" },
  { service: "tree-surgeons", city: "southampton" },
  { service: "architects", city: "southampton" },
  { service: "plasterers", city: "southampton" },
  { service: "kitchen-fitters", city: "southampton" },
  { service: "bathroom-specialists", city: "southampton" },
  { service: "drainage-specialists", city: "southampton" },
  { service: "driveway-specialists", city: "southampton" },
  { service: "window-specialists", city: "southampton" },
  { service: "removal-companies", city: "reading" },
  { service: "cleaners", city: "reading" },
  { service: "tilers", city: "reading" },
  { service: "heating-engineers", city: "reading" },
  { service: "locksmiths", city: "reading" },
  { service: "pest-controllers", city: "reading" },
  { service: "tree-surgeons", city: "reading" },
  { service: "architects", city: "reading" },
  { service: "plasterers", city: "reading" },
  { service: "kitchen-fitters", city: "reading" },
  { service: "bathroom-specialists", city: "reading" },
  { service: "drainage-specialists", city: "reading" },
  { service: "driveway-specialists", city: "reading" },
  { service: "window-specialists", city: "reading" },
  { service: "removal-companies", city: "milton-keynes" },
  { service: "cleaners", city: "milton-keynes" },
  { service: "tilers", city: "milton-keynes" },
  { service: "heating-engineers", city: "milton-keynes" },
  { service: "locksmiths", city: "milton-keynes" },
  { service: "pest-controllers", city: "milton-keynes" },
  { service: "tree-surgeons", city: "milton-keynes" },
  { service: "architects", city: "milton-keynes" },
  { service: "plasterers", city: "milton-keynes" },
  { service: "kitchen-fitters", city: "milton-keynes" },
  { service: "bathroom-specialists", city: "milton-keynes" },
  { service: "drainage-specialists", city: "milton-keynes" },
  { service: "driveway-specialists", city: "milton-keynes" },
  { service: "window-specialists", city: "milton-keynes" },
  { service: "removal-companies", city: "portsmouth" },
  { service: "cleaners", city: "portsmouth" },
  { service: "tilers", city: "portsmouth" },
  { service: "heating-engineers", city: "portsmouth" },
  { service: "locksmiths", city: "portsmouth" },
  { service: "pest-controllers", city: "portsmouth" },
  { service: "tree-surgeons", city: "portsmouth" },
  { service: "architects", city: "portsmouth" },
  { service: "plasterers", city: "portsmouth" },
  { service: "kitchen-fitters", city: "portsmouth" },
  { service: "bathroom-specialists", city: "portsmouth" },
  { service: "drainage-specialists", city: "portsmouth" },
  { service: "driveway-specialists", city: "portsmouth" },
  { service: "window-specialists", city: "portsmouth" },
  { service: "removal-companies", city: "newcastle-upon-tyne" },
  { service: "cleaners", city: "newcastle-upon-tyne" },
  { service: "tilers", city: "newcastle-upon-tyne" },
  { service: "heating-engineers", city: "newcastle-upon-tyne" },
  { service: "locksmiths", city: "newcastle-upon-tyne" },
  { service: "pest-controllers", city: "newcastle-upon-tyne" },
  { service: "tree-surgeons", city: "newcastle-upon-tyne" },
  { service: "architects", city: "newcastle-upon-tyne" },
  { service: "plasterers", city: "newcastle-upon-tyne" },
  { service: "kitchen-fitters", city: "newcastle-upon-tyne" },
  { service: "bathroom-specialists", city: "newcastle-upon-tyne" },
  { service: "drainage-specialists", city: "newcastle-upon-tyne" },
  { service: "driveway-specialists", city: "newcastle-upon-tyne" },
  { service: "window-specialists", city: "newcastle-upon-tyne" },
  { service: "removal-companies", city: "brighton-hove" },
  { service: "cleaners", city: "brighton-hove" },
  { service: "tilers", city: "brighton-hove" },
  { service: "heating-engineers", city: "brighton-hove" },
  { service: "locksmiths", city: "brighton-hove" },
  { service: "pest-controllers", city: "brighton-hove" },
  { service: "tree-surgeons", city: "brighton-hove" },
  { service: "architects", city: "brighton-hove" },
  { service: "plasterers", city: "brighton-hove" },
  { service: "kitchen-fitters", city: "brighton-hove" },
  { service: "bathroom-specialists", city: "brighton-hove" },
  { service: "drainage-specialists", city: "brighton-hove" },
  { service: "driveway-specialists", city: "brighton-hove" },
  { service: "window-specialists", city: "brighton-hove" },
  { service: "removal-companies", city: "sheffield" },
  { service: "cleaners", city: "sheffield" },
  { service: "tilers", city: "sheffield" },
  { service: "heating-engineers", city: "sheffield" },
  { service: "locksmiths", city: "sheffield" },
  { service: "pest-controllers", city: "sheffield" },
  { service: "tree-surgeons", city: "sheffield" },
  { service: "architects", city: "sheffield" },
  { service: "plasterers", city: "sheffield" },
  { service: "kitchen-fitters", city: "sheffield" },
  { service: "bathroom-specialists", city: "sheffield" },
  { service: "drainage-specialists", city: "sheffield" },
  { service: "driveway-specialists", city: "sheffield" },
  { service: "window-specialists", city: "sheffield" },
  { service: "removal-companies", city: "liverpool" },
  { service: "cleaners", city: "liverpool" },
  { service: "tilers", city: "liverpool" },
  { service: "heating-engineers", city: "liverpool" },
  { service: "locksmiths", city: "liverpool" },
  { service: "pest-controllers", city: "liverpool" },
  { service: "tree-surgeons", city: "liverpool" },
  { service: "architects", city: "liverpool" },
  { service: "plasterers", city: "liverpool" },
  { service: "kitchen-fitters", city: "liverpool" },
  { service: "bathroom-specialists", city: "liverpool" },
  { service: "drainage-specialists", city: "liverpool" },
  { service: "driveway-specialists", city: "liverpool" },
  { service: "window-specialists", city: "liverpool" },
  { service: "removal-companies", city: "glasgow" },
  { service: "cleaners", city: "glasgow" },
  { service: "tilers", city: "glasgow" },
  { service: "heating-engineers", city: "glasgow" },
  { service: "locksmiths", city: "glasgow" },
  { service: "pest-controllers", city: "glasgow" },
  { service: "tree-surgeons", city: "glasgow" },
  { service: "architects", city: "glasgow" },
  { service: "plasterers", city: "glasgow" },
  { service: "kitchen-fitters", city: "glasgow" },
  { service: "bathroom-specialists", city: "glasgow" },
  { service: "drainage-specialists", city: "glasgow" },
  { service: "driveway-specialists", city: "glasgow" },
  { service: "window-specialists", city: "glasgow" },
  { service: "removal-companies", city: "edinburgh" },
  { service: "cleaners", city: "edinburgh" },
  { service: "tilers", city: "edinburgh" },
  { service: "heating-engineers", city: "edinburgh" },
  { service: "locksmiths", city: "edinburgh" },
  { service: "pest-controllers", city: "edinburgh" },
  { service: "tree-surgeons", city: "edinburgh" },
  { service: "architects", city: "edinburgh" },
  { service: "plasterers", city: "edinburgh" },
  { service: "kitchen-fitters", city: "edinburgh" },
  { service: "bathroom-specialists", city: "edinburgh" },
  { service: "drainage-specialists", city: "edinburgh" },
  { service: "driveway-specialists", city: "edinburgh" },
  { service: "window-specialists", city: "edinburgh" },
  { service: "removal-companies", city: "nottingham" },
  { service: "cleaners", city: "nottingham" },
  { service: "tilers", city: "nottingham" },
  { service: "heating-engineers", city: "nottingham" },
  { service: "locksmiths", city: "nottingham" },
  { service: "pest-controllers", city: "nottingham" },
  { service: "tree-surgeons", city: "nottingham" },
  { service: "architects", city: "nottingham" },
  { service: "plasterers", city: "nottingham" },
  { service: "kitchen-fitters", city: "nottingham" },
  { service: "bathroom-specialists", city: "nottingham" },
  { service: "drainage-specialists", city: "nottingham" },
  { service: "driveway-specialists", city: "nottingham" },
  { service: "window-specialists", city: "nottingham" },
  { service: "removal-companies", city: "leicester" },
  { service: "cleaners", city: "leicester" },
  { service: "tilers", city: "leicester" },
  { service: "heating-engineers", city: "leicester" },
  { service: "locksmiths", city: "leicester" },
  { service: "pest-controllers", city: "leicester" },
  { service: "tree-surgeons", city: "leicester" },
  { service: "architects", city: "leicester" },
  { service: "plasterers", city: "leicester" },
  { service: "kitchen-fitters", city: "leicester" },
  { service: "bathroom-specialists", city: "leicester" },
  { service: "drainage-specialists", city: "leicester" },
  { service: "driveway-specialists", city: "leicester" },
  { service: "window-specialists", city: "leicester" },
];

export function servicePagePath(service: ServiceSlug) {
  return `/${service}/`;
}

export function localServicePagePath(service: ServiceSlug, city: string) {
  return `/${service}/${city}/`;
}
