import { makeSolihullProfile } from "./solihullProfileBase";

export const bathroomSpecialistsSolihull = makeSolihullProfile("bathroom-specialists", {
  heroCopy: "Planning a bathroom refit in Solihull? Describe the room, sanitaryware, finishes and service changes once, then compare bathroom specialists who cover your area.",
  answer: {
    title: "Looking for a bathroom specialist near you in Solihull?",
    copy: "Enter the postcode and explain whether you need a straight replacement or a full reconfiguration. Mention drainage changes, new electrics, ventilation, tiling, structural work and accessibility needs so suitable Solihull bathroom specialists can price the same scope.",
  },
  localContext: {
    eyebrow: "Solihull bathroom compliance context",
    title: "Solihull Building Control specifically lists new bathrooms among common works requiring approval",
    intro: "A bathroom refit can combine sanitary drainage, electrical work, ventilation, waterproofing and structural changes. Solihull Council explicitly lists new bathrooms among common home improvements requiring Building Regulations approval, so the compliance route should be agreed before finishes cover the work.",
    items: [
      {
        title: "New bathrooms are specifically flagged in Solihull's Building Regulations guidance",
        text: "The council includes new bathrooms in its list of common home improvements that require approval. For a full reconfiguration, ask the contractor which parts are covered by Building Control and which are self-certified through competent-person schemes.",
        source: {
          label: "Solihull Council — do I need Building Regulations approval?",
          url: "https://www.solihull.gov.uk/planning-and-building-control/building-regulations-approval-homeowners/do-i-need-building",
        },
      },
      {
        title: "Strip-out waste from paid work must use a commercial-waste route",
        text: "Solihull Council says rubbish generated by a paid service is commercial rubbish and cannot be taken to the Bickenhill household recycling centre. If the refit includes old suites, tiles, plasterboard or packaging, confirm who is responsible for lawful disposal and whether it is included in the quote.",
        source: {
          label: "Solihull Council — commercial rubbish",
          url: "https://www.solihull.gov.uk/environment-and-animals/commercial-rubbish",
        },
      },
    ],
  },
  areaCopy: {
    intro: "Bathroom specialists may cover Solihull by postcode, room size and scope. Example areas include:",
    sideTitle: "Describe every service change",
    sideCopy: "Moving a WC or shower, adding ventilation, changing electrics and rebuilding a floor is very different from swapping sanitaryware in the same positions. Show the existing layout and the proposed one.",
    noteLead: "Make the compliance responsibility explicit.",
    noteText: "Ask who is handling plumbing, electrics, ventilation, tanking, tiling, Building Regulations evidence and waste so there are no gaps between trades.",
  },
  faq: [
    ["How much does a bathroom refit cost in Solihull?", "The range is wide because layout changes, sanitaryware, tiling, plumbing, electrics, ventilation and structural work all change the scope."],
    ["Does a new bathroom need Building Regulations approval in Solihull?", "Solihull Council lists new bathrooms among common home improvements that require approval."],
    ["Can I post a small shower or toilet replacement?", "Yes. Smaller repairs and replacements can be posted alongside complete bathroom refurbishments."],
    ["Who removes the old suite and tiles?", "Make this explicit in the job. Waste generated by paid work must use a lawful commercial-waste route rather than the household tip."],
    ["Do I have to hire a bathroom specialist who responds?", "No. Up to three interested local professionals can respond and there is no obligation to hire."],
  ],
  cta: {
    title: "Ready to compare bathroom specialists in Solihull?",
    copy: "Describe the bathroom, layout and service changes once, then compare interested Solihull bathroom specialists and their quotes.",
    buttonLabel: "Get Solihull bathroom quotes",
  },
});

export const drainageSpecialistsSolihull = makeSolihullProfile("drainage-specialists", {
  heroCopy: "Need help with blocked drains, recurring flooding, damaged pipes or drainage alterations in Solihull? Describe the symptoms and location once, then compare drainage specialists who cover your area.",
  answer: {
    title: "Looking for a drainage specialist near you in Solihull?",
    copy: "Enter the postcode and explain whether the problem is an internal drain, external gully, sewer connection, surface-water issue or recurring blockage. Mention flooding, smells, backing-up fixtures and previous repairs so suitable Solihull drainage specialists can judge the investigation needed.",
  },
  localContext: {
    eyebrow: "Solihull drainage and flood-risk context",
    title: "Solihull is the Lead Local Flood Authority, with separate responsibilities for sewers, main rivers and ordinary watercourses",
    intro: "The council distinguishes highway and surface-water flooding from Severn Trent sewer issues and Environment Agency main-river flooding. That division matters because a drainage contractor can diagnose the private system, but the responsible authority may change once the defect is beyond the property boundary.",
    items: [
      {
        title: "The responsible organisation depends on the source of flooding",
        text: "Solihull Council says it coordinates local flood risk as Lead Local Flood Authority, while Severn Trent Water handles public sewer and water-main flooding and the Environment Agency manages main-river risk including the River Blythe and River Cole. Record where water first appears and whether neighbours or the highway are affected before commissioning repeated private work.",
        source: {
          label: "Solihull Council — flooding roles and responsibilities",
          url: "https://www.solihull.gov.uk/roads-pavements-and-streetcare/flooding",
        },
      },
      {
        title: "Works affecting an ordinary watercourse can require council consent",
        text: "Solihull Council says its consent may be required before works that affect the flow of an ordinary watercourse. For drainage alterations near a ditch, culvert or small stream, establish whether the proposal is ordinary private drainage work or whether separate LLFA consent is needed.",
        source: {
          label: "Solihull Council — watercourse consenting",
          url: "https://www.solihull.gov.uk/roads-pavements-and-streetcare/flooding/watercourse-consenting",
        },
      },
    ],
  },
  areaCopy: {
    intro: "Drainage specialists may cover Solihull by postcode, problem type and access. Example areas include:",
    sideTitle: "Say exactly where the water backs up",
    sideCopy: "A kitchen waste blockage, collapsed private drain, overflowing highway gully and surface-water flooding need different investigations. Note which fixtures or external points are affected first.",
    noteLead: "Diagnosis before excavation.",
    noteText: "For recurring problems, ask whether CCTV inspection, jetting, tracing, root ingress checks or structural repair are needed before agreeing disruptive work.",
  },
  faq: [
    ["Who deals with sewer flooding in Solihull?", "Solihull Council directs public sewer and water-main flooding to Severn Trent Water, while other flood sources can fall to the council, Environment Agency or landowner."],
    ["Do works to a ditch or small watercourse need consent?", "Potentially. Solihull Council says works affecting an ordinary watercourse may require consent from it as Lead Local Flood Authority."],
    ["Can I post a recurring blocked-drain problem?", "Yes. Explain how often it returns and what previous jetting, CCTV or repairs have already been tried."],
    ["Can tree roots cause drain problems?", "They can enter damaged drainage, but root presence does not by itself prove the tree caused the original defect. A camera survey can help identify the actual pipe condition."],
    ["Do I have to hire a drainage specialist who responds?", "No. Up to three interested local professionals can respond and there is no obligation to hire."],
  ],
  cta: {
    title: "Ready to compare drainage specialists in Solihull?",
    copy: "Describe the symptoms, affected drains and flooding history once, then compare interested Solihull drainage specialists and their quotes.",
    buttonLabel: "Get Solihull drainage quotes",
  },
});
